### ISSUE TITLE
./init.sh says "setting session CLI profile to null" then raises error ProfileNotFound(profile=profile_name)

### ISSUE THREAD

**Issue by syedrakib** [danilop/LambdAuth#46]
```
$ ./init.sh 
setting session CLI profile to null
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 50, in main
    return driver.main()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 176, in main
    parser = self._create_parser()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 157, in _create_parser
    command_table = self._get_command_table()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 91, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 111, in _build_command_table
    command_object=self)
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/session.py", line 684, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/preview.py", line 71, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 349, in service_model
    return self._get_service_model()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 366, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/session.py", line 259, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/session.py", line 280, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/local/aws/local/lib/python2.7/site-packages/botocore/session.py", line 352, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (null) could not be found

```

and this error is shown a million times in the bash whenever `./init.sh` is invoked.

**Comment by syedrakib** [comment]
line no 19 in `config.json` says

`CLI_PROFILE=$(jq -r '.CLI_PROFILE' config.json)`

However, there is no such field called `CLI_PROFILE` defined in `config.json`. Where should this be defined? And what should be its value?

I have my AWS credentials for `aws_access_key_id` and `aws_secret_access_key` defined in my `~/.aws/config` file

**Comment by syedrakib** [comment]
BTW, i am invoking via an IAM role. My IAM role has administrator access. I do not have access to the root account though.

**Comment by syedrakib** [comment]
solved it by adding a `CLI_PROFILE` key in the `config.json` file and setting it's value to `"default"` - because that's the name of the AWS CLI profile i had in my `~/.aws/config` file inside square brackets. 

But this instruction needs to be clearer in the README file and we need to add a `CLI_PROFILE` key in the `config.json` file. Will send a pull request accordingly.

**Comment by syedrakib** [comment]
Pull request here:
https://github.com/danilop/LambdAuth/pull/47

**Comment by syedrakib** [comment]
Relevant pull request #47 has been merged.
